config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :bookings, only: [:index, :update]

  resources :capsules, only: [:show, :index, :new, :create, :destroy] do
    resources :bookings, only: :create
    resources :reviews, only: [:new, :create]
  end
end
  # Defines the root path route ("/")
  # root "posts#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :capsule
  validates :start_date, presence: true
  validates :end_date, presence: true
  # before_save :owner_cannot_book_own_capsule

  STATUSES = ["pending", "approved", "declined"]
  # enum status: %w[pending approved declined]

  private

  # def owner_cannot_book_own_capsule
  #   if current_user.id == self.user_id
  #     errors.add(:owner_error, "Owners cannot book their own capsules")
  #   end
  # end
end

app/models/capsule.rb
class Capsule < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos
  has_many :reviews
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price, presence: true


  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  validates :name, presence: true
  validates :stars, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
  validates :comment, presence: true
  belongs_to :capsule
  end

app/models/user.rb
class User < ApplicationRecord
  has_many :capsules, dependent: :destroy
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def booking_requests
    self.capsules.map do |capsule|
      capsule.bookings.where(status: "pending")
    end.flatten
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protected

  def after_sign_in_path_for(resource)
    if resource.is_a?(User)
      capsules_path
    else
      new_user_session_path
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.status = "pending"
    @capsule = Capsule.find(params[:capsule_id])
    @booking.capsule_id = @capsule.id
    @booking.user_id = current_user.id if @capsule.user_id != current_user.id
    # @booking.capsule = @capsule
    if @booking.save
      flash[:notice] = "Capsule successfully booked!"
      redirect_to dashboard_path
    else
      redirect_to capsule_path(@capsule), status: :unprocessable_entity
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(update_booking_params)
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end

  def update_booking_params
    params.require(:booking).permit(:status)
  end
end

app/controllers/capsules_controller.rb
class CapsulesController < ApplicationController
  def index
    @capsules = Capsule.all
  end

  def new
    @capsule = Capsule.new
  end

  def create
    @capsule = Capsule.new(capsule_params)
    @capsule.user = current_user
    if @capsule.save!
      redirect_to capsule_path(@capsule), notice: "Capsule was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @capsule = Capsule.find(params[:id])
    @booking = Booking.new
    @markers = [{
      lng: @capsule.longitude,
      lat: @capsule.latitude
    }]
  end

  def destroy
    @capsule = Capsule.find(params[:id])
    @capsule.destroy
    redirect_to dashboard_path, status: :see_other
  end

  private

  def capsule_params
    params.require(:capsule).permit(:name, :address, :description, :price, :latitude, :longitude, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
    @capsules = current_user.capsules
    @bookings = current_user.bookings
    @capsule_bookings = Booking.where(capsule_id: @capsules.pluck(:id))
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
      @capsule = Capsule.find(params[:capsule_id])
      @review = @capsule.reviews.build
    end
  
    def create
      @capsule = Capsule.find(params[:capsule_id])
      @review = @capsule.reviews.build(review_params)
  
      if @review.save
        redirect_to @capsule, notice: 'Review added successfully.'
      else
        render :new
      end
    end
  
    private
  
    def review_params
      params.require(:review).permit(:name, :stars, :comment)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<%= render "shared/navbar" %>
<style>
  table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 20px; /* Add some space below the table */
  }
  th, td {
    padding: 8px; /* Add padding to the table cells */
    text-align: left; /* Align text to the left */
    border-bottom: 1px solid #ddd; /* Add bottom border to separate rows */
  }
  th {
    background-color: #f2f2f2; /* Add background color to header row */
  }
</style>

<h1>List of Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Capsule</th>
      <th>Arrival</th>
      <th>Departure</th>
      <th>Status</th> <!-- Add price column header -->
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.capsule_id %></td>
        <td><%= booking.start_date %></td>
        <td><%= booking.end_date %></td>
        <td><%= booking.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/capsules/_form.html.erb
<div class="booking-box border p-4">
  <%= simple_form_for @capsule do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :photos, as: :file, input_html: { multiple: true }, class: "mb-3" %>
    <div class="d-flex">
      <%= f.button :submit, class:'btn button-test' %>
    </div>
    <% end %>

</div>

app/views/capsules/index.html.erb
<%= render "shared/navbar" %>
<div class="container my-5">
  <h1 class="text-center"><strong>Our Capsules</strong></h1>
  <div class="row justify-content-center my-3">
    <% @capsules.each do |capsule| %>
      <div class="col-md-4 mb-4">
        <%= link_to capsule_path(capsule), class: "capsule-card-link" do %>
          <div class="card-trip text-center">
            <div class="card-trip-content">
              <div>
                <h2><%= capsule.name %></h2>
              </div>
                <%# <div class="carousel-item <%= 'active' if index.zero? %>
                <% if capsule.photos.attached? %>
                  <%= cl_image_tag capsule.photos.first.key, style:"height: 400px; width: 100%; object-fit: cover;" %>
                <% else  %>
                  <img src="https://images.unsplash.com/photo-1644299244258-6eff135031e9?q=80&w=2890&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" />
                <% end %>
                <%# </div> %>
              </div>
            <div class="card-trip-infos">
              <h3 class="card-trip-pricing">€<%= capsule.price %></h3>
              <p><%= capsule.address %></p>
              <%# <%= link_to "See more", capsule_path(capsule), class: "btn-outline-pink" %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>





<%# Comment this out for now because it will fail without cloudinary key, get it and put in env file %>
<%#= cl_image_tag @product.photo.key, brightness: 30, radius: 20,
width: 150, height: 150, crop: :thumb, gravity: :face %>

app/views/capsules/new.html.erb
<%= render "shared/navbar" %>
<div class="container mb-5">
  <div class="row justify-content-center p-3">
      <div class="col-md-6">
        <h1>Create a capsule</h1>
        <%= render "form", capsule: @capsule %>
      </div>
  </div>
</div>

app/views/capsules/show.html.erb
<%= render "shared/navbar" %>
<div class="container mb-5">
  <h1 class="mt-4 mb-2 text-start"><%= @capsule.name %></h1>
  <div class="mb-4">
    <i id="show_map" data-action="map#toggleMap" class="fa-solid fa-earth-americas fa-sm" style="color: #bcc5d7; display: inline;"></i>
    <p style="display: inline;"><%= @capsule.address %></p>
  </div>
  <div class="row align-items-start">
    <div class="col-8 pe-5">
      <div id="carouselExampleIndicators" class="text-center carousel slide">
        <div class="carousel-indicators">
          <% @capsule.photos.each_with_index do |photo, index| %>
            <%# <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to='0' class="active" aria-current="true" aria-label="Slide 1"></button> %>
            <%# <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button> %>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="<%= index %>" class="<%= 'active' if index.zero? %>" aria-current="<%= 'true' if index.zero? %>" aria-label="Slide <%= index + 1 %>"></button>
          <% end %>
        </div>
        <div class="carousel-inner">
          <% @capsule.photos.each_with_index do |photo, index| %>
            <div class="carousel-item <%= 'active' if index.zero? %>">
              <%= cl_image_tag photo.key, style:"height: 400px; width: 100%; object-fit: cover;" %>
            </div>
          <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      <h2 class="mt-4">Description</h2>
      <%= @capsule.description %>
    </div>
    <div class="col-4 mt-4 border p-3 booking-box">
      <div class="mb-3">
        <h1 class="text-start" style="display: inline;">€<%= @capsule.price %></h1>
        <p style="display: inline;">/night</p>
      </div>
      <% unless current_user == @capsule.user %>
        <%= simple_form_for([@capsule, @booking], url: capsule_bookings_path(@capsule), method: :post) do |f| %>
          <%= f.input :start_date, as: :date, html5: true, label: 'CHECK-IN', label_html: { style: 'font-size: smaller;' } %>
          <%= f.input :end_date, as: :date, html5: true, label: 'CHECK-OUT', label_html: { style: 'font-size: smaller;' } %>
          <%= f.submit 'Booking', class: 'btn button-test mt-4' %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="mt-4" id="map"
    style="width: 600px; height: 300px;"
    data-controller='map'
    data-map-api-key-value='<%= ENV['MAPBOX_API_KEY'] %>'
    data-map-markers-value='<%= @markers.to_json %>'>
  </div>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CapsuleRooms</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.min.js"></script>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">

    <script src='https://api.mapbox.com/mapbox-gl-js/v2.6.1/mapbox-gl.js'></script>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<%= render "shared/navbar" %>
<div class="container my-5">
  <h1>My Dashboard</h1>
  <div class="row">
    <div class="col-6 my-3 py-3">
      <div class="border rounded bg-light dashboard-card-test">
        <h2 class="dashboard-h2">My Profile</h2>
        <h3>Personal information:</h3>
        <p>Some text or other talking about myself, my name, my cats, and my dreams and hopes</p>
        <h3>My Capsules</h3>
        <ul>
          <% @capsules.each do |capsule| %>
            <li class="capsules-list">
                <%= link_to capsule.name, capsule_path(capsule), class: "link-capsule" %>
                <%= link_to raw('<i class="fa-solid fa-trash"></i>'), capsule_path(capsule), class: "link-delete", data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-6 my-3 py-3">
      <div class="border rounded bg-light dashboard-card-test h-100">
        <h2 class="dashboard-h2">My Upcoming Bookings</h2>
          <ul>
            <% @bookings.each do |booking| %>
              <li><%= booking.capsule.name %> (<%= booking.start_date %> - <%= booking.end_date %>) - <%= booking.status %></li>
            <% end %>
          </ul>
        </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="rounded bg-light dashboard-card-test border">
        <h2 class="dashboard-h2">Manage Bookings Requests</h2>
        <div class="row">
          <% @capsule_bookings.each do |booking| %>
            <div class="col-3">
              <div class="card dashboard-card">
                <h5 class ="card-title"><%= booking.capsule.name %></h5>
                <p class="card-text">Check-in: <%= booking.start_date %></p>
                <p class="card-text mb-3">Check-out: <%= booking.end_date %></p>
                <%= simple_form_for booking do |f| %>
                <div class="d-flex align-items-center">
                  <%= f.input :status, collection: Booking::STATUSES, selected: booking.status, as: :select, include_blank: false, label_html: { class: "d-none" }, wrapper_html: { style: "margin-bottom: 0 !important; flex-grow: 1" } %>
                  <%= f.button :submit, "Update" %>
                </div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <h1><strong>Welcome</strong></h1>
    <p><em>Discover Your Perfect Retreat</em></p>
    <a>
      <% if user_signed_in? %>
        <%= link_to "Find a capsule", capsules_path, class: "btn btn-outline-light" %>
      <% else %>
        <%= link_to "Find a capsule", capsules_path, class: "btn btn-outline-light" %>
      <% end %>
    </a>
  </div>
</div>

app/views/reviews/index.html.erb
<h1>List of reviews</h1>
<% @reviews.each do |review| %>
  <div>
    <strong><%= review.name %></strong> - <%= review.stars %> stars
    <p><%= review.comment %></p>
  </div>
<% end %>

app/views/reviews/new.html.erb
<h1>Leave a review</h1>
<%= form_with(model: [@capsule, @review]) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :stars %>
  <%= form.text_field :stars %>

  <%= form.label :comment %>
  <%= form.text_area :comment %>

  <%= form.submit 'Add review' %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn close" data-bs-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<%# <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%# <%= link_to image_tag("logo2.png", class: "navbar-brand logo-img mx-2") %>
    <%# <% end %>

    <%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> %>

    <%# <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav"> %>
        <%# <% if user_signed_in? %>
          <%# <li class="nav-item active"> %>
            <%# <%= link_to "Home", root_path, class: "nav-link" %>
          <%# </li> %>
          <%# <li class="nav-item active"> %>
            <%# <%= link_to "My Dashboard", dashboard_path, class: "nav-link" %>
          <%# </li>
          <li class="nav-item active"> %>
            <%# <%= link_to "Create a capsule", new_capsule_path, class: "nav-link" %>
          <%# </li>
          <div class ="topnav"> %>
            <%# <% random_avatar_url = "https://picsum.photos/50?random" %>
            <%# <li class="nav-item dropdown">
              <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> %>
                <%# <%= image_tag random_avatar_url, class: "avatar", alt: "dropdown menu" %>
              <%# </a>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown"> %>
                <%# <%= link_to "Action", "#", class: "dropdown-item" %>
                <%# <%= link_to "Another action", "#", class: "dropdown-item" %>
                <%# <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              <%# </div> %>
            <%# </li> %>
          <%# </div> %>

        <%# <% else %>
          <%# <li class="nav-item"> %>
            <%# <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <%# </li> %>
        <%# <% end %>
      <%# </ul>
    </div>
  /div>
div> %>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo6.png", class:'img-logo' %>
      <%# <%= image_tag "logo2.png", class:'img-logo' %>
    <% end %>
    <ul class="navbar-nav me-auto">
      <li class="nav-item active home">
        <%= link_to "Home", capsules_path, class: "nav-link" %>
      </li>
    </ul>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <%# <li class="nav-item active home">
            <%= link_to "Home", root_path, class: "nav-link" %>
          <%# </li> %>
          <li class="nav-item dropdown">
            <% random_avatar_url = "https://picsum.photos/50?random" %>
            <%= image_tag random_avatar_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Create a capsule", new_capsule_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>